### ISSUE TITLE
Cropping is not working properly.

### ISSUE THREAD

**Issue by CemDoganay** [CemDoganay/Dresser_App#10]
we have spent a lot of time to fix the cropping and it is still not working properly. I suggest we take it out.

**Comment by jhowe1998** [comment]
That may well be the case. Although I suggest we can leave the UI for now until we are absolutely certain.

**Comment by bburciaga** [comment]
I concur

**Comment by jhowe1998** [comment]
Whoops my mistake, I didn't mean to reopen this!

**Comment by jhowe1998** [comment]
We made the decision to remove the cropping feature for now.
